apiVersion: v1
kind: Secret
metadata:
  name: chromarag-postgres-secret
  namespace: chromarag
type: Opaque
stringData:
  POSTGRES_USER: chroma
  POSTGRES_PASSWORD: change-me
  POSTGRES_DB: chromarag
  POSTGRES_HOST: postgres.chromarag.svc.cluster.local
